### ISSUE TITLE
Module `Dotenv` not found

### ISSUE THREAD

**Issue by aditya-mitra** [kanishkguptagit/Profiles-rest-api#1]
running `python manage.py migrate` on a fresh environment gives the above error

https://github.com/kanishkguptagit/Profiles-rest-api/blob/master/profiles_project/settings.py#L21-L23

**Comment by kanishkguptagit** [comment]
make .env file then install python-dotenv. 
You need to add DEBUG and SECRET_KEY fields in .env file
